#!/bin/bash
# generate-evidence-bundle.sh
# Generates an evidence artifact bundle for a wave/session by collecting and
# cataloguing all relevant evidence artifacts into a single manifest file.
# Usage: generate-evidence-bundle.sh <wave_id> [output_dir]
# Output: .agent-admin/prehandover/evidence-bundle-<wave_id>.md

set -euo pipefail

WAVE_ID="${1:-}"
OUTPUT_DIR="${2:-.agent-admin/prehandover}"
REPO_ROOT="$(git rev-parse --show-toplevel)"
TIMESTAMP="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
DATE_SLUG="$(date -u +%Y%m%d)"

if [[ -z "$WAVE_ID" ]]; then
  echo "Usage: $0 <wave_id> [output_dir]"
  echo "Example: $0 wave-12 .agent-admin/prehandover"
  exit 1
fi

OUTPUT_FILE="$REPO_ROOT/$OUTPUT_DIR/evidence-bundle-${WAVE_ID}-${DATE_SLUG}.md"
mkdir -p "$REPO_ROOT/$OUTPUT_DIR"

echo "📦 Generating evidence bundle for wave: $WAVE_ID"
echo "   Output: $OUTPUT_FILE"

# Collect evidence artifacts
SESSION_MEMORIES="$(find "$REPO_ROOT/.agent-workspace" -name "session-*.md" -newer "$REPO_ROOT/.git/ORIG_HEAD" -type f 2>/dev/null | sort || find "$REPO_ROOT/.agent-workspace" -name "session-*.md" -type f 2>/dev/null | sort | tail -5)"
IAA_TOKENS="$(find "$REPO_ROOT/.agent-admin/assurance" -name "iaa-token-*.md" -type f 2>/dev/null | sort | tail -3 || true)"
IAA_PREBRIEFS="$(find "$REPO_ROOT/.agent-admin/assurance" -name "iaa-prebrief-*.md" -type f 2>/dev/null | sort | tail -3 || true)"
COMPLETION_REPORTS="$(find "$REPO_ROOT/.agent-admin/completion-reports" -name "*.md" -newer "$REPO_ROOT/.git/ORIG_HEAD" -type f 2>/dev/null | sort || true)"
CANON_INVENTORY="$REPO_ROOT/.governance-pack/CANON_INVENTORY.json"

# Write bundle manifest
cat > "$OUTPUT_FILE" << EOF
# Evidence Artifact Bundle — ${WAVE_ID}

**Generated**: ${TIMESTAMP}
**Wave ID**: ${WAVE_ID}
**Repository**: APGI-cmy/app_management_centre
**Generator**: generate-evidence-bundle.sh

---

## Bundle Summary

This evidence bundle catalogues all governance artifacts produced during wave ${WAVE_ID}.
It is consumed by the merge-gate-interface.yml workflow and the Independent Assurance Agent
to verify completeness before PR merge.

---

## Artifacts

### Session Memories
EOF

if [[ -n "$SESSION_MEMORIES" ]]; then
  while IFS= read -r F; do
    [[ -z "$F" ]] && continue
    RELPATH="${F#$REPO_ROOT/}"
    SIZE="$(wc -c < "$F")"
    echo "- \`$RELPATH\` (${SIZE} bytes)" >> "$OUTPUT_FILE"
  done <<< "$SESSION_MEMORIES"
else
  echo "- _No session memories found_" >> "$OUTPUT_FILE"
fi

cat >> "$OUTPUT_FILE" << EOF

### IAA Tokens
EOF

if [[ -n "$IAA_TOKENS" ]]; then
  while IFS= read -r F; do
    [[ -z "$F" ]] && continue
    RELPATH="${F#$REPO_ROOT/}"
    SIZE="$(wc -c < "$F")"
    echo "- \`$RELPATH\` (${SIZE} bytes)" >> "$OUTPUT_FILE"
  done <<< "$IAA_TOKENS"
else
  echo "- _No IAA tokens found_" >> "$OUTPUT_FILE"
fi

cat >> "$OUTPUT_FILE" << EOF

### IAA Pre-Briefs
EOF

if [[ -n "$IAA_PREBRIEFS" ]]; then
  while IFS= read -r F; do
    [[ -z "$F" ]] && continue
    RELPATH="${F#$REPO_ROOT/}"
    echo "- \`$RELPATH\`" >> "$OUTPUT_FILE"
  done <<< "$IAA_PREBRIEFS"
else
  echo "- _No IAA pre-briefs found_" >> "$OUTPUT_FILE"
fi

cat >> "$OUTPUT_FILE" << EOF

### Completion Reports
EOF

if [[ -n "$COMPLETION_REPORTS" ]]; then
  while IFS= read -r F; do
    [[ -z "$F" ]] && continue
    RELPATH="${F#$REPO_ROOT/}"
    echo "- \`$RELPATH\`" >> "$OUTPUT_FILE"
  done <<< "$COMPLETION_REPORTS"
else
  echo "- _No completion reports found_" >> "$OUTPUT_FILE"
fi

cat >> "$OUTPUT_FILE" << EOF

### CANON_INVENTORY
EOF

if [[ -f "$CANON_INVENTORY" ]]; then
  CANON_SIZE="$(wc -c < "$CANON_INVENTORY")"
  CANON_COUNT="$(python3 -c "import json; d=json.load(open('$CANON_INVENTORY')); print(d.get('total_canons', 'unknown'))" 2>/dev/null || echo "unknown")"
  echo "- \`.governance-pack/CANON_INVENTORY.json\` (${CANON_SIZE} bytes, ${CANON_COUNT} canons)" >> "$OUTPUT_FILE"
else
  echo "- ❌ \`.governance-pack/CANON_INVENTORY.json\` MISSING" >> "$OUTPUT_FILE"
fi

cat >> "$OUTPUT_FILE" << EOF

---

## Validation Checklist

- [ ] All session memories committed
- [ ] IAA token present and PASS verdict
- [ ] Prehandover proof committed (immutable after initial commit)
- [ ] CANON_INVENTORY.json present and non-stub
- [ ] No open HALT conditions in session

---

*Auto-generated by generate-evidence-bundle.sh at ${TIMESTAMP}*
EOF

echo ""
echo "✅ Evidence bundle generated: $OUTPUT_FILE"
echo ""
cat "$OUTPUT_FILE"
